apiVersion: v1
kind: Pod
metadata:
  name: watcher

  labels:
    app: watcher

spec:
  containers:
    - name: watcher

      image: watcher:latest
      imagePullPolicy: Never
      command: ["/app/main"]
      env:
        - name: DEBUG
          value: "false"
      volumeMounts:
        - mountPath: /secret
          name: mysecret
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - all
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
  securityContext:
    fsGroup: 10000

  volumes:
  - name: mysecret
    secret:
      secretName: mysecret
      defaultMode: 0440
